[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://lzzeoqrwrepscujqbnzg.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_ceRXMcmGppWFkbGuz3pXOg_yaoym6b6"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
